[workspace]
members = [
  "ncrs_core",
  "ncrs-gui/src-tauri",
  "plugins/ncrs_plugin",
  "plugins/nc_passwords",
  "plugins/nc_gnome_integration",
]
resolver = "2"

[workspace.package]
version = "0.1.73" # x-release-please-version
edition = "2021"
authors = ["Gonzalo Ruiz <foss@rgon.es>"]
license = "GPL-3.0-or-later"

[workspace.dependencies]
clap = "4.5.40"
